### ISSUE TITLE
Can't use it, can't update it

### ISSUE THREAD

**Issue by hikuikuma** [oddbear/Loupedeck.VolumeControl.Plugin#3]
Hello, I installed the plugin a while ago, but overnight, Loupedeck showed me this message:

> **One or more plugins were not loaded**
> The following plugins were not loaded because they had malfunctioned: Volume Control

Since then, an update has been released but when I click on "update" in the marketplace, it attempts the update before telling me :

> **Plug-in installation failed**
> Unfortunately, the plug-in installation in VolumeControl failed. Please contact its developer for assistance.

And I also can't uninstall the plugin.

**Comment by oddbear** [comment]
Hi, thanks for reaching out.

This issue is something that has happened lately with at least two of my plugins, and I am not sure why yet.
I am trying to figure it out, but I have not been able to reproduce it yet.

For the uninstall / reinstall, please go to:
C:\Users\oddbj\AppData\Local\Loupedeck\Logs\plugin_crashes
and delete whatever you find there... oddbj is my user, so yours will be a little different.

If that does not help, then try deleting the plugin folder (same as uninstall):
C:\Users\oddbj\AppData\Local\Loupedeck\Plugins\VolumeControl
(again oddbj is my username, so it will be different, one way to navigate here is to write %localappdata% in windows explorer)

Both needs a restart of the Loupedeck software to work.

If you find any logs and want to share, that could be very helpful.
C:\Users\oddbj\AppData\Local\Loupedeck\Logs

This is an interesting issue. :)

**Comment by hikuikuma** [comment]
Hello, I looked in the plugin_crashes folder, it was empty! So I deleted the VolumeControl folder and reinstalled the plugin from the marketplace and it works, thank you!

I am attaching yesterday's logs where the plugin was unusable, impossible to uninstall and update if that helps ;)

Best regards

[2023-03-14T21-00-15-2223_LoupedeckServiceTool.log](https://github.com/oddbear/Loupedeck.VolumeControl.Plugin/files/12607913/2023-03-14T21-00-15-2223_LoupedeckServiceTool.log)
